name: "Build"

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

# List supported ROCm GPU targets in ROCm 6.4.2, and also some unsupported ones that might work
# See https://rocm.docs.amd.com/en/latest/compatibility/compatibility-matrix.html and https://rocm.docs.amd.com/en/docs-6.4.2/reference/gpu-arch-specs.html
# gfx950 is supported in 7.1.0 but not 6.4.2 that we're using
# Fully supported GPU targets (runtime & SDK): gfx1030 gfx1100 gfx1101 gfx1102 gfx1151 gfx1200 gfx1201
# Runtime supported GPU targets: gfx1031 gfx1032
# Unsupported GPU targets that probably won't work: gfx803 gfx900 gfx906 gfx908 gfx90a gfx942 gfx950 gfx1010 gfx1011 gfx1012 gfx1150 gfx1152
# Non-working GPU targets that have caused build failures: gfx950 gfx1010
env:
  AMD_GPU_TARGETS: "gfx1030;gfx1031;gfx1032;gfx1100;gfx1101;gfx1102;gfx1150;gfx1151;gfx1152;gfx1200;gfx1201"
  CUDAARCHS: "50-virtual;60-virtual;61;70-virtual;75;80;86;89;120a-real"

jobs:
  BuildMac:
    runs-on: "macos-15-intel" # CT2 only builds x86_64 correctly on an x86_64 host

    strategy:
      matrix:
        config:
          - "Release"

    steps:
      - name: "Get version"
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]
          then version="${GITHUB_REF#refs/tags/}"
          else version=master
          fi
          echo "version=$version" > "$GITHUB_OUTPUT"
        id: "get-version"

      - uses: maxim-lobanov/setup-xcode@v1.6.0
        id: set-xcode-version
        with:
          xcode-version: 16.2

      - uses: "actions/checkout@v4"

      - name: "Run CT2 build"
        run: "./build_ct2_macos.sh ${{ matrix.config }}  ${{ steps.get-version.outputs.version }}"

      - name: "Run SP build"
        run: "./build_sp_macos.sh ${{ matrix.config }}  ${{ steps.get-version.outputs.version }}"

      - uses: "actions/upload-artifact@v4"
        with:
          name: "libraries-macos-${{ matrix.config }}-${{ steps.get-version.outputs.version }}"
          path: "dist/*.tar.gz"

  BuildLinux:
    if: false
    runs-on: "ubuntu-22.04"

    strategy:
      matrix:
        config:
          - "Debug"
          - "Release"

    steps:
      - name: "Get version"
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]
          then version="${GITHUB_REF#refs/tags/}"
          else version=master
          fi
          echo "version=$version" > "$GITHUB_OUTPUT"
        id: "get-version"

      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - name: "Run build-linux.sh"
        run: "./build-linux.sh ${{ matrix.config }} ${{ steps.get-version.outputs.version }}"

      - uses: "actions/upload-artifact@v4"
        with:
          name: "libcurl-linux-${{ matrix.config }}"
          path: "dist/*.tar.gz"

  BuildWindows:
    runs-on: "windows-2022"

    strategy:
      matrix:
        config:
          - "Release"
        accel: [generic, nvidia, amd]

    steps:
      - name: "Get version"
        shell: bash
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]
          then version="${GITHUB_REF#refs/tags/}"
          else version=master
          fi
          echo "version=$version" > "$GITHUB_OUTPUT"
        id: "get-version"

      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - name: Setup CUDA Toolkit
        if: ${{ matrix.accel == 'nvidia' }}
        id: cuda-toolkit
        shell: pwsh
        run: ./setup_cuda.ps1
        env:
            INPUT_CUDA_VERSION: 12.8.1

      - name: Set CUDA_TOOLKIT_ROOT_DIR if CUDA is installed
        if: ${{ matrix.accel == 'nvidia' }}
        run: |
          "CUDA_TOOLKIT_ROOT_DIR=$env:CUDA_PATH" >> $env:GITHUB_ENV

      - name: Install AMD hip SDK v7.1.1
        id: depends-hipblas
        if: ${{ matrix.accel == 'amd' }}
        run: |
          $ErrorActionPreference = "Stop"
          write-host "Downloading AMD HIP SDK Installer"
          Invoke-WebRequest -Uri "https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-26.Q1-Win11-For-HIP.exe" -OutFile "${env:RUNNER_TEMP}\rocm-install.exe"
          write-host "Installing AMD HIP SDK"
          Start-Process "${env:RUNNER_TEMP}\rocm-install.exe" -ArgumentList '-install' -NoNewWindow -Wait
          write-host "Completed AMD HIP SDK installation"

      - name: Verify ROCm
        id: verify-hipblas
        if: ${{ matrix.accel == 'amd' }}
        run: |
          & 'C:\Program Files\AMD\ROCm\*\bin\clang.exe' --version

      - name: Prepare hipBLAS environment
        id: prepare-hipblas
        if: ${{ matrix.accel == 'amd' }}
        run: |
          "HIP_PATH=$(Resolve-Path 'C:\Program Files\AMD\ROCm\*\bin\clang.exe' | split-path | split-path)" >> $env:GITHUB_ENV

      - name: "Run Build CT2 Windows ps1"
        run: "./build_ct2_windows.ps1 -Configuration ${{ matrix.config }} -Acceleration ${{ matrix.accel }}"

      - name: "Run Build SP Windows ps1"
        run: "./build_sp_windows.ps1 -Configuration ${{ matrix.config }}"

      - uses: "actions/upload-artifact@v4"
        with:
          name: "libctranslate2-windows-${{ matrix.config }}-${{ matrix.accel }}"
          path: "dist/*.zip"

  Release:
    runs-on: "ubuntu-22.04"
    if: "github.event_name == 'push' && contains(github.ref, 'refs/tags/')"
    needs: [BuildMac, BuildWindows] #TODO: BuildLinux
    permissions:
      contents: "write"
    defaults:
      run:
        shell: bash
    steps:
      - name: "Get Metadata"
        id: "metadata"
        run: |
          echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: "Download build artifacts"
        uses: "actions/download-artifact@v4"

      - name: Generate Checksums 🪪
        run: |
          : Generate Checksums 🪪
          if [[ "${RUNNER_DEBUG}" ]]; then set -x; fi
          shopt -s extglob

          echo "### Checksums" > ${{ github.workspace }}/CHECKSUMS.txt
          for file in $( find ${{ github.workspace }} -name "*.tar.gz" -o -name "*.zip" ); do
            echo "    ${file##*/}: $(sha256sum "${file}" | cut -d " " -f 1)" >> ${{ github.workspace }}/CHECKSUMS.txt
          done

      - name: "Create Release"
        uses: "softprops/action-gh-release@v2"
        with:
          draft: true
          tag_name: "${{ steps.metadata.outputs.version }}"
          name: "${{ steps.metadata.outputs.version }}"
          body_path: ${{ github.workspace }}/CHECKSUMS.txt
          files: |
            ${{ github.workspace }}/**/*.tar.gz
            ${{ github.workspace }}/**/*.zip
